version: "3.8"
services:
  tiks_db:
    container_name: tiks_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tiks_baza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: limun
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  tiks_pgadmin4:
    container_name: tiks_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: zeljadelija01@gmail.com
      PGADMIN_DEFAULT_PASSWORD: limun
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data:
